version: "3"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: KONNECT
    volumes:
      - ./server/pgdata/:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  server:
    depends_on:
      - db
    restart: always
    build: ./server/
    container_name: server
    volumes:
      - ./server/res/:/app/res
    env_file:
        - .env
    ports:
      - 3000:3000
