version: "3"

services:
  database:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: KONNECT
    volumes:
      - ./backend/pgsetup/:/docker-entrypoint-initdb.d/
      - ./backend/pgdata/:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
